### PR TITLE
Sorted issue with PostgreSQL

### LINKED ISSUE #89: postgres errors during cronjob
I noticed in my nextcloud log that an error is happening during the cronjob. It is happening because at some point the query `INSERT INTO "oc_login_address_aggregated" ("uid", "ip", "seen", "first_seen", "last_seen") VALUES($1, $2, $3, $4, $5)` tries to insert a duplicate value for `(uid, ip)` which violates a unique key defined on that table.
Am running nextcloud 16.0.1 on a linux server with nginx and postgres 10.8.
```
Error	core	Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT "seen", "first_seen", "last_seen" FROM "oc_login_address_aggregated" WHERE ("uid" = ?) AND ("ip" = ?)' with params ["***redacted***", "***redacted***"]: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 184:

    Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException("An exceptio ... k", Doctrine\DBA ... ]})

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 158:

    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBA ... {}, Doctrine\DBA ... ]}, "An exceptio ... k")

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 938:

    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBA ... {}, Doctrine\DBA ... ]}, "SELECT \"se ... )", { 1: "***redacted*** ... "})

    /var/www/nextcloud/lib/private/DB/Connection.php - line 195:

    Doctrine\DBAL\Connection->executeQuery("SELECT \"se ... )", [ "***redacted*** ... "], [ 2,2], null)

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 219:

    OC\DB\Connection->executeQuery("SELECT \"se ... )", { uid: "***redacted*** ... "}, [])

    /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 214:

    Doctrine\DBAL\Query\QueryBuilder->execute()

    /var/www/nextcloud/apps/suspicious_login/lib/Service/ETLService.php - line 134:

    OC\DB\QueryBuilder\QueryBuilder->execute()

    /var/www/nextcloud/apps/suspicious_login/lib/BackgroundJob/ETLJob.php - line 51:

    OCA\SuspiciousLogin\Service\ETLService->extractAndTransform()

    /var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 77:

    OCA\SuspiciousLogin\BackgroundJob\ETLJob->run(null)

    /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php - line 59:

    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

    /var/www/nextcloud/cron.php - line 123:

    OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

Cased by Doctrine\DBAL\Driver\PDOException: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 930:

    Doctrine\DBAL\Driver\PDOStatement->execute()

    /var/www/nextcloud/lib/private/DB/Connection.php - line 195:

    Doctrine\DBAL\Connection->executeQuery("SELECT \"se ... )", [ "***redacted*** ... "], [ 2,2], null)

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 219:

    OC\DB\Connection->executeQuery("SELECT \"se ... )", { uid: "***redacted*** ... "}, [])

    /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 214:

    Doctrine\DBAL\Query\QueryBuilder->execute()

    /var/www/nextcloud/apps/suspicious_login/lib/Service/ETLService.php - line 134:

    OC\DB\QueryBuilder\QueryBuilder->execute()

    /var/www/nextcloud/apps/suspicious_login/lib/BackgroundJob/ETLJob.php - line 51:

    OCA\SuspiciousLogin\Service\ETLService->extractAndTransform()

    /var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 77:

    OCA\SuspiciousLogin\BackgroundJob\ETLJob->run(null)

    /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php - line 59:

    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

    /var/www/nextcloud/cron.php - line 123:

    OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

Cased by PDOException: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php - line 141:

    PDOStatement->execute(null)

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 930:

    Doctrine\DBAL\Driver\PDOStatement->execute()

    /var/www/nextcloud/lib/private/DB/Connection.php - line 195:

    Doctrine\DBAL\Connection->executeQuery("SELECT \"se ... )", [ "***redacted*** ... "], [ 2,2], null)

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 219:

    OC\DB\Connection->executeQuery("SELECT \"se ... )", { uid: "***redacted*** ... "}, [])

    /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 214:

    Doctrine\DBAL\Query\QueryBuilder->execute()

    /var/www/nextcloud/apps/suspicious_login/lib/Service/ETLService.php - line 134:

    OC\DB\QueryBuilder\QueryBuilder->execute()

    /var/www/nextcloud/apps/suspicious_login/lib/BackgroundJob/ETLJob.php - line 51:

    OCA\SuspiciousLogin\Service\ETLService->extractAndTransform()

    /var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 77:

    OCA\SuspiciousLogin\BackgroundJob\ETLJob->run(null)

    /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php - line 59:

    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

    /var/www/nextcloud/cron.php - line 123:

    OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
```

### PR DESCRIPTION
**Pull request by adi-dev**
Fixes #89

Two changes now: 
- Changed way to insert or update logins from `try{insert}catch(exception){update)` to `if(is null select){insert}else{update}`
- `fetch()` doesn't produce any results so using `fetchAll()` instead.
This time it's working on my setup, populates `login_address_aggregated` with data

### CODE REVIEW

File: lib/Service/ETLService.php [hunk 1]
```diff
@@ -120,23 +120,18 @@ public function extractAndTransform(int $max = self::MAX_BATCH_SIZE, OutputInter
...
-			$insert->setParameter('ip', $row['ip']);
-			$insert->setParameter('seen', 1, IQueryBuilder::PARAM_INT);
-			$insert->setParameter('ts', $row['created_at'], IQueryBuilder::PARAM_INT);
-
-			try {
+			$select
+				->setParameter('uid', $row['uid'])
+				->setParameter('ip', $row['ip']);
+			$result = $select->execute();
+			$existing = $result->fetchAll()[0];
```
Comment (ChristophWurst) [inline lib/Service/ETLService.php]: :warning: this will fetch more than one row at a time. But you only use the first one.

Actually, `->fetch` should be fine and only return `null` if there was no data that matches the query or the cursor was moved to the end of the current result set during iteration.

Comment (adi-dev) [reply lib/Service/ETLService.php]: I understand but, at least on my machine (PHP7.2FPM) the `fetch()` in conjunction with `is_null` was failing regardless if it had any results or not and in effect it tried to update non existing rows. I figured that if I use `fetchAll()` instead it works.

File: lib/Service/ETLService.php [hunk 2]
```diff
@@ -120,23 +120,19 @@ public function extractAndTransform(int $max = self::MAX_BATCH_SIZE, OutputInter
...
-			$insert->setParameter('seen', 1, IQueryBuilder::PARAM_INT);
-			$insert->setParameter('ts', $row['created_at'], IQueryBuilder::PARAM_INT);
-
-			try {
+			$select
+				->setParameter('uid', $row['uid'])
+				->setParameter('ip', $row['ip']);
+			$result = $select->execute();
+			$existing = $result->fetch();
+			$result->closeCursor();
```
Comment (adi-dev) [inline lib/Service/ETLService.php]: After running tests and analysing others code, I found that there was `closeCursor()` statement

File: lib/Service/ETLService.php (hunk 1 above)
Comment (adi-dev) [reply lib/Service/ETLService.php]: After running tests and analysing others code, I found that there was `closeCursor()` statement
```suggestion
			$result->closeCursor();
```

**Comment by adi-dev** [comment]
Hi @ChristophWurst, any progress on this, did you had a chance to review? It's working here, but I only have two machines, both with PostgreSQL. Cheers.

File: lib/Service/ETLService.php [hunk 3]
```diff
@@ -120,23 +120,19 @@ public function extractAndTransform(int $max = self::MAX_BATCH_SIZE, OutputInter
...
-				$select
-					->setParameter('uid', $row['uid'])
-					->setParameter('ip', $row['ip']);
-				$result = $select->execute();
-				$existing = $result->fetch();
-				if (is_null($existing)) {
-					continue;
-				}
-
+			}else{
```
Comment (ChristophWurst) [inline lib/Service/ETLService.php]:
```suggestion
			} else {
```
