### PR TITLE
fix(IPv6): Ignore scope identifier in IPv6 addresses

### LINKED ISSUE #1087: Caught unknown error during IPv6 background training: Invalid IPv6 address
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Install Suspicious Login app on Nextcloud 32.0.6
2. Check logs
3. See `Caught unknown error during IPv6 background training`
```json
{
   "app": "suspicious_login",
   "exception": {
      "Code": 0,
      "CustomMessage": "Caught unknown error during IPv6 background training",
      "exception": [],
      "Exception": "InvalidArgumentException",
      "File": "/var/www/nextcloud/apps/suspicious_login/lib/Service/IpV6Strategy.php",
      "Line": 39,
      "message": "Caught unknown error during IPv6 background training",
      "Message": "Invalid IPv6 address",
      "Trace": [
         {
            "class": "OCA\\SuspiciousLogin\\Service\\IpV6Strategy",
            "file": "/var/www/nextcloud/apps/suspicious_login/lib/Service/AClassificationStrategy.php",
            "function": "ipToVec",
            "line": 38,
            "type": "->"
         },
         {
            "class": "OCA\\SuspiciousLogin\\Service\\AClassificationStrategy",
            "file": "/var/www/nextcloud/apps/suspicious_login/lib/Service/DataLoader.php",
            "function": "newVector",
            "line": 92,
            "type": "->"
         },
         {
            "args": [
               "*** sensitive parameters replaced ***"
            ],
            "class": "OCA\\SuspiciousLogin\\Service\\DataLoader",
            "function": "OCA\\SuspiciousLogin\\Service\\{closure}",
            "type": "->"
         },
         {
            "file": "/var/www/nextcloud/apps/suspicious_login/lib/Service/DataLoader.php",
            "function": "array_map",
            "line": 90
         },
         {
            "class": "OCA\\SuspiciousLogin\\Service\\DataLoader",
            "file": "/var/www/nextcloud/apps/suspicious_login/lib/Service/DataLoader.php",
            "function": "addressesToDataSet",
            "line": 69,
            "type": "->"
         },
         {
            "class": "OCA\\SuspiciousLogin\\Service\\DataLoader",
            "file": "/var/www/nextcloud/apps/suspicious_login/lib/Service/TrainService.php",
            "function": "loadTrainingAndValidationData",
            "line": 51,
            "type": "->"
         },
         {
            "class": "OCA\\SuspiciousLogin\\Service\\TrainService",
            "file": "/var/www/nextcloud/apps/suspicious_login/lib/BackgroundJob/TrainJobIpV6.php",
            "function": "train",
            "line": 47,
            "type": "->"
         },
         {
            "class": "OCA\\SuspiciousLogin\\BackgroundJob\\TrainJobIpV6",
            "file": "/var/www/nextcloud/lib/public/BackgroundJob/Job.php",
            "function": "run",
            "line": 61,
            "type": "->"
         },
         {
            "class": "OCP\\BackgroundJob\\Job",
            "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
            "function": "start",
            "line": 97,
            "type": "->"
         },
         {
            "class": "OCP\\BackgroundJob\\TimedJob",
            "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
            "function": "start",
            "line": 84,
            "type": "->"
         },
         {
            "class": "OCP\\BackgroundJob\\TimedJob",
            "file": "/var/www/nextcloud/cron.php",
            "function": "execute",
            "line": 175,
            "type": "->"
         }
      ]
   },
   "id": "69a7f9a601a47",
   "level": 3,
   "message": "Caught unknown error during IPv6 background training",
   "method": "",
   "occ_command": [
      "/var/www/nextcloud/cron.php"
   ],
   "remoteAddr": "",
   "reqId": "WN37vLGnPsd1vVGaEdBg",
   "scriptName": "/var/www/nextcloud/cron.php",
   "time": "2026-03-04T03:25:01+00:00",
   "url": "--",
   "user": "--",
   "userAgent": "--",
   "version": "32.0.6.1"
}
```

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead, if possible also add a screenshot

### Server configuration

**Web server:** Apache

**Database:** Maria

**PHP version:** 8.3.6

**Nextcloud version:** 32.0.6

<details>
<summary>List of activated apps</summary>

```
Enabled:
  - activity: 5.0.0
  - admin_audit: 1.22.0
  - appointments: 2.6.3
  - audioplayer: 3.7.0
  - autocurrency: 1.6.8
  - bookmarks: 16.1.3
  - bruteforcesettings: 5.0.0
  - calendar: 6.2.1
  - camerarawpreviews: 0.8.8
  - checksum: 2.0.3
  - cloud_federation_api: 1.16.0
  - comments: 1.22.0
  - contacts: 8.3.4
  - contactsinteraction: 1.13.1
  - cospend: 3.2.0
  - dashboard: 7.12.0
  - data_request: 4.0.1
  - dav: 1.34.2
  - deck: 1.16.3
  - dicomviewer: 2.3.2
  - external: 7.0.0
  - extract: 1.3.6
  - facerecognition: 0.9.70
  - federatedfilesharing: 1.22.0
  - files: 2.4.0
  - files_accesscontrol: 3.0.2
  - files_antivirus: 6.1.0
  - files_automatedtagging: 3.0.3
  - files_downloadlimit: 5.0.0-dev.0
  - files_external: 1.24.1
  - files_pdfviewer: 5.0.0
  - files_retention: 3.0.0
  - files_sharing: 1.24.1
  - files_trashbin: 1.22.0
  - files_versions: 1.25.0
  - firstrunwizard: 5.0.0
  - forms: 5.2.4
  - gpxpod: 7.2.4
  - impersonate: 3.0.1
  - integration_discourse: 3.1.0
  - integration_github: 3.2.2
  - integration_gitlab: 4.0.0
  - keeweb: 0.6.22
  - logreader: 5.0.0
  - lookup_server_connector: 1.20.0
  - mail: 5.7.1
  - memories: 7.8.2
  - notes: 4.13.0
  - notifications: 5.0.0
  - notify_push: 1.3.0
  - oauth2: 1.20.0
  - password_policy: 4.0.0
  - phonetrack: 1.0.1
  - photos: 5.0.0
  - polls: 8.6.3
  - previewgenerator: 5.13.0
  - privacy: 4.0.0
  - profile: 1.1.0
  - provisioning_api: 1.22.0
  - recognize: 10.0.7
  - recommendations: 5.0.0
  - related_resources: 3.0.0
  - serverinfo: 4.0.0
  - settings: 1.15.1
  - sharebymail: 1.22.0
  - side_menu: 5.2.1
  - spreed: 22.0.9
  - survey_client: 4.0.0
  - suspicious_login: 10.0.0
  - systemtags: 1.22.0
  - text: 6.0.1
  - theming: 2.7.0
  - timemanager: 0.3.22
  - twofactor_backupcodes: 1.21.0
  - twofactor_totp: 14.0.0
  - updatenotification: 1.22.0
  - viewer: 5.0.0
  - weather_status: 1.12.0
  - workflowengine: 2.14.0
```
</details>

<details>
<summary>Nextcloud configuration</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_CF_CONNECTING_IP",
            "HTTP_X_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.sitnikov.eu",
        "dbtype": "mysql",
        "version": "32.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filesystem_check_changes": 0,
        "filelocking.enabled": true,
        "bulkupload.enabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5
        },
        "default_phone_region": "DE",
        "maintenance": false,
        "theme": "",
        "logfile": "\/var\/nextcloud\/data\/nextcloud.log",
        "loglevel": 1,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "logfile_audit": "\/var\/nextcloud\/data\/audit.log",
        "trashbin_retention_obligation": "14, auto",
        "versions_retention_obligation": "14, auto",
        "data-fingerprint": "7be51475e95ea13b254cd880319d98ec",
        "remember_login_cookie_lifetime": "60*60*24*7",
        "files.chunked_upload.max_size": 52428800,
        "token_auth_enforced": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Image"
        ],
        "preview_max_x": 1920,
        "preview_max_y": 1080,
        "jpeg_quality": 90,
        "auth.bruteforce.protection.enabled": true,
        "simpleSignUpLink.shown": false,
        "profile.enabled": false,
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": true,
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "has_rebuilt_cache": true,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "gpxedit",
            "extract",
            "dicomviewer",
            "facerecognition"
        ],
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.ffmpeg_path": "\/usr\/bin\/ffmpeg",
        "memories.ffprobe_path": "\/usr\/bin\/ffprobe",
        "memories.tmp_path": "\/tmp",
        "memories.transcoder": "\/var\/www\/nextcloud\/apps\/memories\/exiftool-bin\/go-vod-amd64",
        "memories.no_transcode": false,
        "memories.qsv": true,
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.db.triggers.fcu": true,
        "memories.gis_type": 1,
        "maintenance_window_start": 2,
        "defaultapp": "dashboard,files",
        "forbidden_filename_basenames": [
            "con",
            "prn",
            "aux",
            "nul",
            "com0",
            "com1",
            "com2",
            "com3",
            "com4",
            "com5",
            "com6",
            "com7",
            "com8",
            "com9",
            "com\u00b9",
            "com\u00b2",
            "com\u00b3",
            "lpt0",
            "lpt1",
            "lpt2",
            "lpt3",
            "lpt4",
            "lpt5",
            "lpt6",
            "lpt7",
            "lpt8",
            "lpt9",
            "lpt\u00b9",
            "lpt\u00b2",
            "lpt\u00b3"
        ],
        "forbidden_filename_characters": [
            "<",
            ">",
            ":",
            "\"",
            "|",
            "?",
            "*",
            "\\",
            "\/"
        ],
        "forbidden_filename_extensions": [
            " ",
            ".",
            ".filepart",
            ".part"
        ]
    }
}
```
</details>

### PR DESCRIPTION
**Pull request by DerDreschner**
- Resolves #1087 

## Summary

IPv6 addresses may contain a scope identifier at the end (e.g., `%eth1`, see [RFC 4007](https://datatracker.ietf.org/doc/html/rfc4007)). This case isn't handled by our code right now and throws an `InvalidArgumentException`. As workaround, I would suggest stripping the scope entirely.

Integrating it into the current model isn't very practical in my opinion, as the length of the scope identifier isn't limited and we can only use a few characters before the vector dimensions grow too large.

AI-assisted: Claude Code (claude-sonnet-4-6)

### CODE REVIEW

File: lib/Util/IPv6AddressParser.php [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+	 * filter out the scope, as the current model doesn't support
+	 * processing this information.
+	 */
+	public static function stripScopeIdentifier(string $address): string {
+		$delimiterPosition = strpos($address, '%');
+		$scopeIdentifierExists = $delimiterPosition !== false;
+
+		return $scopeIdentifierExists
+			? substr($address, 0, $delimiterPosition)
+			: $address;
```
Comment (ChristophWurst) [inline lib/Util/IPv6AddressParser.php:25]: nit, non-blocking: this could be a nice use case for the `match` expression and matching on the strpos: false -> keep as is, else transform

**Review by ChristophWurst — APPROVED** [review]
Good catch and nice fix
