### PR TITLE
fix(32bit): drop darsyn/ip dependency

### LINKED ISSUE #837: Investigate feasibility of use in 32-bit environments
A single dependency that appears to only be used for IPv6 handling currently has a requirement for a 64-bit environment.

This came up during nextcloud/server#43157 (and further context can bge found there).

- Is this still a hard requirement today?
- How much work would it take to support IPv6 w/o this requirement?
- Would it make any sense to adapt the app to still function in 32-bit IPv4-only environments?

### PR DESCRIPTION
**Pull request by st3iny**
Fix #837
Fix https://github.com/nextcloud/server/issues/43157

Parse IPv6 addresses directly using built-in functions. I compared both binary representations of hundreds of random IPv6 addresses and they are exactly the same so we don't need to drop trained models.

Ref https://www.php.net/manual/en/function.inet-pton.php

---

Can be tested via:
```
occ suspiciouslogin:seed --v6
occ suspiciouslogin:train --v6
```

### CODE REVIEW

File: lib/Service/IpV6Strategy.php [hunk 1]
```diff
@@ -50,8 +51,12 @@ public function findHistoricAndRecent(LoginAddressAggregatedMapper $loginAddress
 	}
 
 	protected function ipToVec(string $ip): array {
-		$addr = IPv6::factory($ip);
-		$hex = bin2hex($addr->getBinary());
+		$addr = inet_pton($ip);
+		if ($addr === false) {
+			throw new InvalidArgumentException('Invalid IPv6 address');
```
Comment (st3iny) [inline lib/Service/IpV6Strategy.php:56]: @ChristophWurst Maybe you have a better idea on how to handle this a bit more gracefully?

Comment (joshtrichards) [reply lib/Service/IpV6Strategy.php:56]: Doesn't look like `inet_pton` can fail on anything other than a truly invalid IP address value provided to it... Which seems highly unlikely given the source: either `REMOTE_ADDR` as provided directly by the web server (based on the functioning client IP connection) or from a proxy provided header (set also based on the actual connection there from the client). 

So in the unlikely event it does fail, something is **very very** wrong (so a hard exception seems desirable + acceptable IMO).

Comment (ChristophWurst) [reply lib/Service/IpV6Strategy.php:56]: I think this approach is fine. `\Darsyn\IP\Version\IPv6::factory` would through too :+1:

**Review by ChristophWurst — APPROVED** [review]

**Comment by st3iny** [comment]
**Do not** install the app from the app store. It is shipped starting from Nextcloud 25 and will be updated automatically every time you update your Nextcloud server.

How to get this fix? -> Wait for the next Nextcloud patch or minor release and install it.

Please refer to https://github.com/nextcloud/suspicious_login?tab=readme-ov-file#installation for more information.

**Comment by bcutter** [comment]
OK thanks that was pretty helpful.

...BUT it does not fully answer my question.

27.1.6 does not contain it (obviously, as me updating to that release initially discovered this dependency issue which lead to this fix in the end), BUT https://github.com/nextcloud/server/releases/tag/v27.1.7rc1 does not either.

So let me specify my question: **when will this fix arrive in which stable (series 27) release?**

**Comment by st3iny** [comment]
It should be included in [27.1.7 RC1](https://github.com/nextcloud/server/pull/43480) and will be included in the final 27.1.7 release.

Testing an RC is always welcome but you are on your own risk.

**Comment by bcutter** [comment]
I can't see it in the https://github.com/nextcloud/server/releases/tag/v27.1.7rc1 release notes. Maybe I'm missing something.

**Comment by bcutter** [comment]
Also nothing in https://github.com/nextcloud/server/releases/tag/v27.1.7rc2

Now https://github.com/nextcloud/server/releases/tag/v27.1.7 is out.

How can one be sure this fix is actually part of 27.1.7?

**Comment by st3iny** [comment]
The changelog is not extensive and it is included in the final release of 27.1.7.

**Comment by bcutter** [comment]
Confirmed working (27.1.7.2 update).
